name: sonar
on: push
jobs:
  runtests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pdm sync -d -G testing
      - name: Run Tests
        run: |
          pdm run testci
          pdm run testreport
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets. SONAR_TOKEN}}
      - name: Publish package
        run: |
          pdm plugin add pdm-publish
          pdm publish --password ${{ secrets.PYPI_TOKEN }}